DROPOUT = 0.5
REG_ALPHA = 0.000
LAYERS = 1

# fit
BATCH_SIZE = 2
NB_EPOCH = 1

SAVE_EVERY_NB_ITERATIONS = int(100/BATCH_SIZE)

# fit_generator
BATCH_SIZE_GENERATOR = 64  # ~10 sec
NB_EPOCH_GENERATOR = 6*60*0.1
MAX_Q_SIZE = 1
NB_WORKER = 1
PICKLE_SAFE = False

SAMPLES_TO_TEST = 1000
